name: oshmes_terminal
description: Oshmes terminal
publish_to: "none"
version: 1.1.2+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_pty: ^0.4.0
  get_it: ^7.6.0
  super_drag_and_drop: ^0.4.0
  gesture_x_detector: ^1.1.1
  super_context_menu: ^0.1.0
  xterm:
    # path: ../xterm.dart
    git:
      url: https://github.com/freethinkel/xterm.dart.git
      ref: master
  rxdart: ^0.27.7
  yaml: ^3.1.2
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  collection: ^1.17.1
  multi_split_view: ^2.4.0
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "lib/assets/app_icon/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: TablerIcons
      fonts:
        - asset: lib/assets/fonts/tabler-icons.woff2
  shaders:
    - shaders/glitch.glsl
  assets:
    - lib/assets/
    - lib/modules/theme/themes/
